### 直接测试 Python FastAPI
POST http://127.0.0.1:8000/ask
Content-Type: application/json
X-API-Key: dev-secret-key

{
  "question": "RAG 的核心流程是什么？"
}

### 测试 Java Spring 转发
POST http://127.0.0.1:8080/api/chat
Content-Type: application/json

{
  "question": "RAG 的核心流程是什么？"
}

### 直接测试 Python FastAPI ask-agent
POST http://127.0.0.1:8000/ask-agent
Content-Type: application/json
X-API-Key: dev-secret-key

{
  "question": "RAG 的核心流程是什么？"
}

### 直接测试 Python FastAPI ask-agent 不调用tool工具
POST http://127.0.0.1:8000/ask-agent
Content-Type: application/json
X-API-Key: dev-secret-key

{
  "question": "你好，你能做什么？"
}

### classic RAG，流式返回
POST http://127.0.0.1:8000/ask/stream
Content-Type: application/json
X-API-Key: dev-secret-key

{
  "question": "RAG 的核心流程是什么？"
}


### java转发SSE，流式返回
POST http://127.0.0.1:8080/api/chat/stream
Content-Type: application/json
X-API-Key: dev-secret-key

{
  "question": "RAG 的核心流程是什么？"
}
